services:
  - type: web
    name: games-sync
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: ADMIN_KEY
        sync: false
      - key: DATA_ENCRYPTION_KEY
        sync: false
      - key: DATABASE_PATH
        value: /var/data/games-sync.localdb
    disk:
      name: games-sync-data
      mountPath: /var/data
      sizeGB: 1
